# Generated by Django 5.2.6 on 2025-09-20 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_short_code', models.CharField(max_length=10)),
                ('account_reference', models.CharField(max_length=50)),
                ('transaction_desc', models.CharField(max_length=100)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
